version: "3.8"

services:
  app:
    build:
      context: .          
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - DATABASE_TEST_URL=postgresql://${POSTGRES_TEST_USER}:${POSTGRES_TEST_PASSWORD}@db_test:${POSTGRES_TEST_PORT}/${POSTGRES_TEST_DB}
    depends_on:
      - db
      - db_test
    ports:
      - "${FASTAPI_PORT}:80"
    env_file:
      - "./.env"

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - "./.env"

  db_test:
    image: postgres:17
    container_name: postgres_db_test
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_TEST_PORT}:${POSTGRES_TEST_PORT}"
    env_file:
      - "./.env"

volumes:
  postgres_data:
  postgres_test_data:
